services:
  overturemaps-downloader:
    build: 
      context: overturemaps-downloader
    env_file:
      - .env
    volumes:
      - ./data:/data
  gdal:
    image: ghcr.io/osgeo/gdal:alpine-small-latest
    volumes:
      - ./data:/data
